RUN_NPM = npm

install:
	$(RUN_NPM) install

build:
	$(RUN_NPM) run build

test:
	$(RUN_NPM) test

lint:
	$(RUN_NPM) run lint

fmt:
	$(RUN_NPM) run fmt

.env:
	$(RUN_NPM) run .env

run:
	$(RUN_NPM) start