FROM node:16.0.0-slim

WORKDIR /server
COPY . .
COPY .yarnrc.yml .
COPY .yarn/releases/ .yarn/releases/
RUN yarn install
RUN yarn build
RUN chown -R node /server
USER node
CMD exec node --conditions=transpiled apps/core/dist/index.js